# Github Action YML CS 491 Final Project, Ernesto Bernardo
# Push to Docker after successful tests

name: CI to Docker Hub

on:
  workflow_run:
    workflows: ["Decision Tree Build and Test"]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cs491-final-project:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
